version: '3.9'

services:
  db:
    image: mysql:8
    container_name: howlive-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: youngw0130!
      MYSQL_DATABASE: howlive
    ports:
      - "3308:3306
    volumes:
      - howlive_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build: .
    container_name: howlive-app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/app

volumes:
  howlive_data: